course_index:
    path:     /
    defaults: { _controller: "CleverBirdBundle:Course:index" }
    methods:  GET

course_show:
    path:     /{id}/show
    defaults: { _controller: "CleverBirdBundle:Course:show" }
    methods:  GET

course_participants:
    path:     /{id}/participants
    defaults: { _controller: "CleverBirdBundle:Course:participants" }
    methods:  GET

course_enroll:
    path:     /{id}/enroll
    defaults: { _controller: "CleverBirdBundle:Course:enroll" }
    methods:  GET

course_new:
    path:     /new
    defaults: { _controller: "CleverBirdBundle:Course:new" }
    methods:  [GET, POST]

course_edit:
    path:     /{id}/edit
    defaults: { _controller: "CleverBirdBundle:Course:edit" }
    methods:  [GET, POST]

course_delete:
    path:     /{id}/delete
    defaults: { _controller: "CleverBirdBundle:Course:delete" }
    methods:  DELETE
