course_lecture_show:
    path:     /{id}/show
    defaults: { _controller: "CleverBirdBundle:Lecture:show", light: false }
    methods:  GET

course_lecture_show_light:
    path:     /{id}/show.light
    defaults: { _controller: "CleverBirdBundle:Lecture:show", light: true }
    methods:  GET

course_lecture_new:
    path:     /new
    defaults: { _controller: "CleverBirdBundle:Lecture:new" }
    methods:  [GET, POST]

course_lecture_edit:
    path:     /{id}/edit
    defaults: { _controller: "CleverBirdBundle:Lecture:edit" }
    methods:  [GET, POST]

course_lecture_delete:
    path:     /{id}/delete
    defaults: { _controller: "CleverBirdBundle:Lecture:delete" }
    methods:  DELETE
