<?php

namespace CleverBirdBundle\Entity;

/**
 * UserRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find latest registered users.
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findLatestUsers()
    {
        $repository = $this->getEntityManager()->getRepository('AuthorBundle:User');

        $query = $repository->createQueryBuilder('e')
            ->andWhere('e.isActive = true')
            ->orderBy('e.id', 'desc')
            ->setMaxResults(5);
        $query->getQuery()->useResultCache(true, 36000)->useQueryCache(true);

        return $query->getQuery()->getResult();
    }

    /**
     * Find latest registered users.
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findTopUsers()
    {
        $repository = $this->getEntityManager()->getRepository('AuthorBundle:User');

        $query = $repository->createQueryBuilder('e')
            ->select('e')
            ->andWhere('e.isActive = true')
            ->addSelect('COUNT(m.id) as hidden posts_count')
            ->join('e.posts', 'm')
            ->groupBy('e.id')
            ->orderBy('posts_count', 'desc')
            ->setMaxResults(5);

        $query->getQuery()->useResultCache(true, 36000)->useQueryCache(true);

        return $query->getQuery()->getResult();
    }
}
