clever_bird_course:
    resource: "@CleverBirdBundle/Resources/config/routing/course.yml"
    prefix:   /course

clever_bird_homepage:
    path:     /
    defaults: { _controller: CleverBirdBundle:Default:index }

courses_list:
    path: /courses-list
    defaults: { _controller: CleverBirdBundle:Default:coursesList }

registration:
    path: /registration
    defaults: { _controller: CleverBirdBundle:Security:register }

login:
    path: /login
    defaults: { _controller: CleverBirdBundle:Security:login }

login_check:
    path: /login_check
    defaults: { _controller: Cl:Security:loginCheck }

logout:
    path: /logout
